sudo: required

services:
  - docker

env:
  - NAME=elasticsearch TAGS="livingdocs/elasticsearch:latest livingdocs/elasticsearch:1.7 livingdocs/elasticsearch:1.7.5"

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t $NAME .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      for tag in ($TAGS); do
        docker tag $NAME $tag
        docker push $tag;
      done
    fi
